### ISSUE TITLE
Failed to fetch Meridian packages

### ISSUE THREAD

**Issue by rsagaga** [PsychoTea/MeridianJB#35]
Both Meridian sources are not fetching and they are not showing any packages after refreshing. I have refreshed it both on safe-mode and jailbreak-mode. I even tried doing this :

1st Method:

1.  Closed Cydia
2.  Ran iCleaner Pro (twice)
3.  Respring
4.  Open Cydia
5.  Refresh
6.  Still nothing.

2nd Method:

1. Closed Cydia
2. Ran iCleaner
3. Delete Meridian
4. Re-Load using Cydia Impactor
5. Going to through the Meridian steps
6. Open and refreshed
7. Still nothing.

![img_3888](https://user-images.githubusercontent.com/42829115/44833537-316db780-abe3-11e8-9543-f8cc79382015.PNG)

Please Help. Thanks

**Comment by Siguza** [comment]
This is a server-side error - the SSL certificate has expired. We'll have to wait for @PsychoTea to fix it.

**Comment by rsagaga** [comment]
whew! here I thought I did something wrong. thanks

**Comment by Siguza** [comment]
Looks like this has been resolved. :)
