### ISSUE TITLE
Backboardd hooking not working with Meridian v0.9-006

### ISSUE THREAD

**Issue by ajorpheus** [PsychoTea/MeridianJB#39]
**Issue**
	Backboardd hooking does not work with Meridian. This prevents AutoTouch from working (and potentially other tweaks as well which depend on this). Note that, AutoTouch works fine with older and newer Jailbreaks (for example, works fine with Yalu, Electra, Double Helix to name a few relatively recent ones) 

**Instructions to reproduce**
	As you suggested, Kent Krantz (author of AutoTouch) has created a simple tweak to demonstrate this issue: https://github.com/kentkrantz/testbackboarddhooking

**Details**
	AutoTouch Version 4.3.4-6+debug (https://beta.autotouch.net/)
	Meridian (@ibsparkes) (v0.9-006, https://meridian.sparkes.zone/)
	iPhone 7+ 
	iOS 10.3.1

**Contact**
	Kent Krantz (
			Discord: Kent Krantz#4444
			https://www.reddit.com/user/kentkrantz
			https://twitter.com/kentkrantz?lang=en
			https://github.com/kentkrantz
	)

**Comment by ahanank** [comment]
Same issue here :(

**Comment by ajorpheus** [comment]
This is fixed in the substrate branch!
