### ISSUE TITLE
Can't compile from source

### ISSUE THREAD

**Issue by m0420** [PsychoTea/MeridianJB#41]
When trying to compile from source I get over 40 compiling errors on Xcode 9.4.1

Is another version of Xcode [10] needed?

**Comment by PsychoTea** [comment]
You don't need Xcode 10.

What errors are you getting? Are you missing headers?

**Comment by m0420** [comment]
Most of them are:
"Implicit conversion loses integer precision: "unsigned long long" to "uint32_t" (aka unsigned int") in vortex.m

Others are the use of undeclared identifier "thread _state" in kernel.m

Last error is given by Apple LLVM 9.0 in Xcode: Too many errors emitted, stopping now

**Comment by m0420** [comment]
I close this issue as it is a stupid user error
